version: '3.8'
services:

  db:
    platform: linux/x86_64
    image: "mysql:5.7"
    ports:
      - 3306:3306
    #volumes:
      #- C:\Users\hp\Documents\kevin\backend\src\main\resources\db=/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user

  backend:
    depends_on:
      - db
    build: ./backend
    restart: always
    environment:
      spring.datasource.url: jdbc:mysql://db:3306/test
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 8080:8080

  frontend:
    depends_on:
      - db
    build: ./frontend
    ports:
      - 4200:80
    
#volumes:
  #db_data=C:\Users\hp\Documents\kevinbackend\src\main\resources\db