version: "3.9"

services:

  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
#    descomentar para crear un volumen de datos para nuestra base de datos
#    nos permite conservar los datos de nuestro contenedor de bd
#    volumes:
#      - ./mysql-data:/var/lib/mysql
#      - C:\Users\hp\Documents\kevin\backend\src\main\resources\db=/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - TZ=UTC
#    networks:
#      - app-network
    #restart: always

  backend:
    depends_on:
      - db
    build: ./backend
    restart: always
    environment:
     - DATABASE_URL=jdbc:mysql://db:3306/test
     - MYSQL_USER=root
     - MYSQL_PASSWORD=root
#    - DATABASE_URL=jdbc:mysql://db:3306/test?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    ports:
      - 8080:8080
#    networks:
#      - app-network

  frontend:
    depends_on:
      - db
    build: ./frontend
    ports:
      - 4200:80
#    networks:
#      - app-network

#networks:
#  app-network:
#    driver: bridge
    
